server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mycat:8066/highway_etc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: etcuser
    password: etcpass
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 32
      minimum-idle: 8
      connection-timeout: 30000
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

maintenance:
  retention-days: 3
  cleanup-interval-ms: 1800000 # 30 minutes
